
export const types = {
    login:'[Auth] Login',
    logout: '[Auth] Logout',
    uiStartLoading: '[UI] Start Loading',
    uiFinishLoading: '[UI] Finish Loading',
    loadData: '[Data] Load Data',
    removeData: '[Data] Remove Data',
    updateImg: '[editData] Update Img',
    updateUser: '[editData] Update User',
    updateData: '[editData] Update Data',
    loadCourse: '[courseData] Load Courses',
    addCourse: '[courseData] Add Course',
    deleteCourse: '[courseData] Delete Course',
    removeCourses: '[courseData] Remove Courses',
    updateCourse: '[courseData] Update Course',
    loadHobbie: '[hobbieData] Load Hobbie',
    addHobbie: '[hobbieData] Add Hobbie',
    deleteHobbie: '[hobbieData] Delete Hobbie',
    removeHobbies: '[hobbieData] Remove Hobbies',
    updateHobbie: '[hobbieData] Update Hobbie', 
    loadStudie: '[studieData] Load Studie',
    addStudie: '[studieData] Add Studie',
    deleteStudie: '[studieData] Delete Studie',
    removeStudies: '[studieData] Remove Studies',
    updateStudie: '[studieData] Update Studie', 
    loadLanguages: '[studieData] Load Studie',
    addLanguage: '[studieData] Add Studie',
    deleteLanguage: '[studieData] Delete Studie',
    removeLanguages: '[studieData] Remove Studies',
    updateLanguage: '[studieData] Update Studie', 
}