
export const types = {
    login:'[Auth] Login',
    logout: '[Auth] Logout',
    uiSetError: '[UI] Set Error',
    uiRemoveError: '[UI] Remove Error',
    uiStartLoading: '[UI] Start Loading',
    uiFinishLoading: '[UI] Finish Loading',
    loadData: '[Data] Load Data',
    removeData: '[Data] Remove Data',
    updateImg: '[editData] Update Img',
    updateUser: '[editData] Update User',
    updateData: '[editData] Update Data',
    loadCourse: '[courseData] Load Courses',
    addCourse: '[courseData] Add Course',
    deleteCourse: '[courseData] Delete Course',
    removeCourses: '[courseData] Remove Courses',
    updateCourse: '[courseData] Update Course',
    loadHobbie: '[hobbieData] Load Hobbie',
    addHobbie: '[hobbieData] Add Hobbie',
    deleteHobbie: '[hobbieData] Delete Hobbie',
    removeHobbies: '[hobbieData] Remove Hobbies',
    updateHobbie: '[hobbieData] Update Hobbie', 
    loadStudie: '[studieData] Load Studie',
    addStudie: '[studieData] Add Studie',
    deleteStudie: '[studieData] Delete Studie',
    removeStudies: '[studieData] Remove Studies',
    updateStudie: '[studieData] Update Studie', 
    loadLanguages: '[languagesData] Load Language',
    addLanguage: '[languagesData] Add Language',
    deleteLanguage: '[languagesData] Delete Language',
    removeLanguages: '[languagesData] Remove Languages',
    updateLanguage: '[languagesData] Update Language',
    loadPost: '[postData] Load Post', 
    addPost: '[postData] Add Post', 
    deletePost: '[postData] Delete Post',
    removePost: '[postData] Remove Post',  
    addComment: '[commentData] Add Comment', 
    deleteComment: '[commentData] Delete Comment', 
    loadComment: '[commentData] Load Comment',
    loadAllComment: '[commentData] Load All Comment',
    removeComment: '[commentData] Remove Comment',  
    removeCommentPost: '[commentData] Remove Comment Post', 
}